[package]
name = "anymon-runner"
description = "File watching, event filtering and task supervision for anymon."
readme = "README.md"
keywords = ["watcher", "file-watcher", "notify", "task-runner"]
categories = ["development-tools", "filesystem"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
anymon-config = { workspace = true }
anymon-shell = { workspace = true }
anyhow = { workspace = true }
colored = { workspace = true }
globset = { workspace = true }
ignore = { workspace = true }
notify = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
