# GitHub Sponsors configuration
# See https://docs.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

# Replace with your GitHub username
github: builtbyjonas
