[package]
name = "anymon-core"
description = "Ultra-fast, language-agnostic file watcher that runs anything on change."
readme = "README.md"
keywords = ["watcher", "file-watcher", "hot-reload", "cli", "nodemon"]
categories = ["command-line-utilities", "development-tools"]
default-run = "anymon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[[bin]]
name = "anymon"
path = "src/main.rs"

[dependencies]
anymon-config = { workspace = true }
anymon-runner = { workspace = true }
anymon-shell = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
colored = { workspace = true }
flate2 = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
ureq = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
