[package]
name = "anymon-config"
description = "Configuration schema, parsing and discovery for anymon."
readme = "README.md"
keywords = ["config", "toml", "watcher"]
categories = ["config", "development-tools"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
anyhow = "1.0.104"

[dev-dependencies]
tempfile = { workspace = true }
